version: 2

install_composer: &install_composer
    run: |
        cd /tmp
        EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
        then
            >&2 echo 'ERROR: Invalid installer signature'
            rm composer-setup.php
            exit 1
        fi
        sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
        RESULT=$?
        rm composer-setup.php
        exit $RESULT

jobs:
  build:
    docker:
      - image: circleci/php:7.2-browsers

    working_directory: ~/networq-web

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-composer-{{ checksum "composer.json" }}
          - v1-npm-{{ checksum "package.json" }}
          - v1-composer-
          - v1-npm-

      - run:
        <<: *install_composer

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-composer-{{ checksum "composer.json" }}

      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-{{ checksum "package.json" }}

      - run: ./vendor/bin/grumphp run
